package main

import (
	"fmt"
	"net/http"
	"time"

	log "github.com/rokmetro/logging-library/loglib"
)

type handlerFunc = func(*log.Log, http.ResponseWriter, *http.Request)

type WebAdapter struct {
	logger *log.Logger
}

func (we WebAdapter) Start() {
	// Empty permissions indicates that no permissions are required
	http.HandleFunc("/test", we.wrapFunc(we.test))

	http.ListenAndServe(":5000", nil)
}

// test endpoint tests logging
func (we WebAdapter) test(l *log.Log, w http.ResponseWriter, req *http.Request) {
	param := req.URL.Query().Get("param")
	l.AddContext("param", param)

	err := checkParam(param)
	if err != nil {
		l.RequestErrorAction(w, log.ActionValidate, log.TypeQueryParam, nil, err, http.StatusBadRequest, false)
		return
	}

	l.Info("Success")

	l.RequestSuccess(w)
}

func checkParam(param string) error {
	if param == "test" {
		return nil
	}

	return log.DataError(log.StatusInvalid, log.TypeArg, &log.FieldArgs{"param": param})
}

// wrapFunc provides a standard wrapper that performs request logging
func (we WebAdapter) wrapFunc(handler handlerFunc) http.HandlerFunc {
	// Receive request with tokens generated by auth service
	return func(w http.ResponseWriter, req *http.Request) {
		logObj := we.logger.NewRequestLog(req)

		logObj.RequestReceived()
		handler(logObj, w, req)
		logObj.RequestComplete()
	}
}

// NewWebAdapter creates new WebAdapter instance
func NewWebAdapter(logger *log.Logger) WebAdapter {
	return WebAdapter{logger: logger}
}

func main() {
	//Instantiate a logger for each service
	var logger = log.NewLogger("health-service", nil)
	logger.SetLevel(log.Debug)

	var random = 1234
	logger.Infof("Starting service: %d", random)
	logger.InfoWithFields("ENV_VAR", log.Fields{"name": "test", "val": 123})

	go CallTest()

	// Instantiate and start a new WebAdapter
	adapter := NewWebAdapter(logger)
	adapter.Start()
}

func CallTest() (*http.Response, error) {
	time.Sleep(2 * time.Second)

	req, err := http.NewRequest("GET", "http://127.0.0.1:5000/test", nil)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Authorization", "example_token")
	req.Header.Set("Header", "test")
	req.Header.Set("span-id", "4313")

	q := req.URL.Query()
	q.Add("param", "test")
	req.URL.RawQuery = q.Encode()

	fmt.Println(req.URL.String())

	client := &http.Client{}
	return client.Do(req)
}
